server:
  port: 8888

spring:
  rabbitmq:
    addresses: amqp://guest:guest@localhost:5672/middleware
    ssl:
      verify-hostname: false

channel:
  generic:
    name: generic
    context:
      - generic_exchange
  specific:
    name: specific
    context:
      - notification
      - vasco
